before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
  goarch:
    - amd64
  ldflags:
    - -s -w -X github.com/choppedpork/ohctl/cmd.version={{.Version}} -X github.com/choppedpork/ohctl/cmd.commit={{.ShortCommit}} -X github.com/choppedpork/ohctl/cmd.date={{.Date}}
brew:
  github:
    owner: choppedpork
    name: homebrew-tap
  homepage: "https://github.com/choppedpork/ohctl"
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
