language: go

go:
  - stable
  - tip

before_install:
  - go get -t -v ./...

script:
  - ./go_test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux